export const GET_TASKS = 'tasks_getthem'
export const LOADING = 'tasks_loading'
export const ERROR = 'tasks_error'
export const CHANGE_USER_ID = 'tasks_change_user_id'
export const CHANGE_TITLE = 'tasks_change_title'
export const SAVED = 'tasks_saved'
